//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketHos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> IdPatient { get; set; }
        public Nullable<int> IdSpecialist { get; set; }
        public Nullable<int> IdTime { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Specialist Specialist { get; set; }
        public virtual Time Time { get; set; }
    }
}
