//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketHos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketEntities : DbContext
    {
        public TicketEntities()
            : base("name=TicketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Specialist> Specialist { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Time> Time { get; set; }
    }
}
